# Python W4 - Assignment 01

## Q1:  Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [ ]:
# Ans:
import numpy as np
a=np.ones((3,3))
print('Checkerboard pattern')
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

Checkerboard pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q2: Create a 2d array with 1 on the border and 0 inside

In [ ]:
# Ans:
import numpy as np
x=np.ones((5,5))
print('Original array:')
print(x)
print('1 on the border and 0 inside in the array')
x[1:-1,1:-1]=0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q3: Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# Ans
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Q4: Create a vector with values ranging from 10 to 49 and then reverse the vector.

In [ ]:
# Ans
import numpy as np
x=np.arange(10,49)
print('Original vector:')
print(x)
print('All values reverse the vector:')
print(x[::-1])

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
All values reverse the vector:
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Q5: Find indices of non-zero elements from the numpy array - [1,2,0,0,4,0]

In [ ]:
# Ans
import numpy as np
x=np.array([1,2,0,0,4,0])
np.where(x==0)[0]


array([2, 3, 5])

## Q6: Import the pandas library, import the absenteeism dataset(provided) and assign it to “df”, and find out the “type” of the dataset.

In [ ]:
# Ans
from google.colab import files
upload=files.upload()




Saving Absenteeism_data.csv to Absenteeism_data.csv


In [ ]:
import pandas as pd
df=pd.read_csv("Absenteeism_data.csv")
type(df)
df.head(10)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   
5   3                  23  10/07/2015                     179   
6  10                  22  17/07/2015                     361   
7  20                  23  24/07/2015                     260   
8  14                  19  06/07/2015                     155   
9   1                  22  13/07/2015                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8  
7         4     0                          4  
8         2     0                         40  
9         1     1                          8

## Q7: Find the info of the data set.

In [ ]:
# Ans
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Reason for Absence         700 non-null    int64  
 1   Date                       700 non-null    object 
 2   Transportation Expense     700 non-null    int64  
 3   Distance to Work           700 non-null    int64  
 4   Daily Work Load Average    700 non-null    float64
 5   Body Mass Index            700 non-null    int64  
 6   Education                  700 non-null    int64  
 7   Children                   700 non-null    int64  
 8   Pets                       700 non-null    int64  
 9   Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(8), object(1)
memory usage: 54.8+ KB


## Q8: Drop the first column “ID”, and save it back to “df”.

In [ ]:
# Ans
df_drop_ID=df.drop('ID',axis=1)
df_drop_ID

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                    26  07/07/2015                     289                36   
1                     0  14/07/2015                     118                13   
2                    23  15/07/2015                     179                51   
3                     7  16/07/2015                     279                 5   
4                    23  23/07/2015                     289                36   
..                  ...         ...                     ...               ...   
695                  10  23/05/2018                     179                22   
696                   6  23/05/2018                     225                26   
697                  10  24/05/2018                     330                16   
698                  23  24/05/2018                     235                16   
699                  28  31/05/2018                     291                31   

     Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0     33                  239.554               30          1         2     1   
1     50                  239.554               31          1         1     0   
2     38                  239.554               31          1         0     0   
3     39                  239.554               24          1         2     0   
4     33                  239.554               30          1         2     1   
..   ...                      ...              ...        ...       ...   ...   
695   40                  237.656               22          2         2     0   
696   28                  237.656               24          1         1     2   
697   28                  237.656               25          2         0     0   
698   32                  237.656               25          3         0     0   
699   40                  237.656               25          1         1     1   

     Absenteeism Time in Hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
695                          8  
696                          3  
697                          8  
698                          2  
699                          2  

[700 rows x 11 columns]

## Q9: Drop the age column. And save it back to “df”

In [ ]:
# Ans
df_drop_Age=df.drop('Age',axis=1)
df_drop_Age

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Daily Work Load Average  Body Mass Index  Education  \
0                  36                  239.554               30          1   
1                  13                  239.554               31          1   
2                  51                  239.554               31          1   
3                   5                  239.554               24          1   
4                  36                  239.554               30          1   
..                ...                      ...              ...        ...   
695                22                  237.656               22          2   
696                26                  237.656               24          1   
697                16                  237.656               25          2   
698                16                  237.656               25          3   
699                31                  237.656               25          1   

     Children  Pets  Absenteeism Time in Hours  
0           2     1                          4  
1           1     0                          0  
2           0     0                          2  
3           2     0                          4  
4           2     1                          2  
..        ...   ...                        ...  
695         2     0                          8  
696         1     2                          3  
697         0     0                          8  
698         0     0                          2  
699         1     1                          2  

[700 rows x 11 columns]

## Q10 What are the smallest and largest values of the column “reason for absence”.

In [ ]:
# Ans
col_max_val=df['Reason for Absence'].max(axis=0)
print('Largest value of column:',col_max_val)


Largest value of column: 28


In [ ]:
col_min_val=df['Reason for Absence'].min(axis=0)
print('Smallest value of column:',col_min_val)

Smallest value of column: 0
